name = "OTUanalysis"
uuid = "8b275fd3-10b2-4c13-b7ff-b6e82f020bf9"
authors = ["svdobbert <sdobbert@uni-bonn.de>"]
version = "0.1.0"

[deps]
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
CSVFiles = "5d742f6a-9f54-50ce-8119-2520741973ca"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
GZip = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
Jchemo = "fbca9394-dd0a-4d1c-b066-ae75f6ef1ad5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"

[compat]
Arrow = "2.8.0"
CSVFiles = "1.0.2"
CategoricalArrays = "0.10.8"
ColorSchemes = "3.28.0"
Compose = "0.9.5"
DataFrames = "1.7.0"
Dates = "1.11.0"
Downloads = "1.6.0"
GZip = "0.6.2"
Gadfly = "1.4.0"
Jchemo = "0.8.4"
LinearAlgebra = "1.8.5"
MLJ = "0.20.0"
Missings = "1.2.0"
MultivariateStats = "0.10.3"
Plots = "1.40.9"
Statistics = "1.8.5"
Tar = "1.10.0"
